In [1]:
#import libraries
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

In [4]:
#Import dataset
import pandas as pd
ds=pd.read_csv("product_dataset_Task2.csv")
ds.head(5)#only top of 5 dataset show

,CustomerID,Product,Price,Quantity,City,PurchaseDate
0,1052,Desktop,NaN,4.0,Bangalore,2021-06-30
1,1041,Desktop,NaN,3.0,Delhi,2023-01-21
2,1057,Smartphone,forty-five thousand,2.0,Bangalore,2023-04-06
3,1038,Tablet,45000.0,1.0,Chennai,2023-07-05
4,1013,Smartphone,45000.0,NaN,Mumbai,2022-04-11

In [17]:
print(ds.to_string())

     CustomerID     Product    Price Quantity       City PurchaseDate
0          1052     Desktop  30000.0      4.0  Bangalore   2021-06-30
1          1041     Desktop  30000.0      3.0      Delhi   2023-01-21
2          1057  Smartphone  30000.0      2.0  Bangalore   2023-04-06
3          1038      Tablet  45000.0      1.0    Chennai   2023-07-05
4          1013  Smartphone  45000.0      NaN     Mumbai   2022-04-11
5          1094      Laptop  60000.0      two     Mumbai   2022-03-12
6          1004      Laptop  30000.0      2.0    Chennai   2022-02-25
7          1034      Laptop  30000.0      2.0    Chennai   2022-12-22
8          1086      Laptop  30000.0      3.0      Delhi   2022-10-23
9          1092     Desktop  30000.0      3.0     Mumbai   2022-03-12
10         1074      Laptop  45000.0      NaN  Bangalore   2021-08-14
11         1017     Desktop  45000.0      NaN       Pune   2022-08-09
12         1075     Desktop  30000.0      1.0       Pune   2021-09-28
13         1008      Laptop  60000.0      1.0    Chennai   2021-09-13
14         1073      Laptop  15000.0      NaN      Delhi   2021-01-01
15         1057      Tablet  15000.0      NaN       Pune   2022-11-22
16         1016  Smartphone  60000.0      4.0     Mumbai   2023-09-03
17         1006      Laptop  30000.0      3.0    Chennai   2022-07-10
18         1045      Tablet  45000.0      1.0  Bangalore   2023-01-21
19         1012      Tablet  15000.0      3.0    Chennai   2023-07-20
20         1039  Smartphone  30000.0      3.0  Bangalore   2021-02-15
21         1041     Desktop  30000.0      NaN    Chennai   2021-01-01
22         1008      Laptop  60000.0      4.0    Chennai   2021-04-16
23         1049  Smartphone  30000.0      2.0    Chennai   2022-02-25
24         1026      Laptop  15000.0      4.0  Bangalore   2023-03-22
25         1065      Tablet  30000.0      4.0  Bangalore   2021-01-31
26         1004      Tablet  15000.0      3.0    Chennai   2022-04-11
27         1028     Desktop  60000.0      4.0       Pune   2021-05-16
28         1036      Tablet  60000.0      1.0      Delhi   2022-05-11
29         1037      Tablet  30000.0      3.0      Delhi   2023-03-22
30         1082  Smartphone  30000.0      1.0      Delhi   2022-04-11
31         1007      Laptop  30000.0      2.0  Bangalore   2023-01-06
32         1064      Laptop  30000.0      3.0  Bangalore   2021-04-01
33         1085  Smartphone  30000.0      2.0       Pune   2021-04-16
34         1016     Desktop  45000.0      3.0      Delhi   2023-08-19
35         1070      Laptop  45000.0      NaN      Delhi   2023-04-21
36         1088      Tablet  45000.0      4.0    Chennai   2023-09-18
37         1044      Laptop  45000.0      NaN  Bangalore   2023-05-21
38         1003      Tablet  15000.0      2.0      Delhi   2023-12-02
39         1035     Desktop  45000.0      4.0       Pune   2023-03-07
40         1069  Smartphone  60000.0      3.0       Pune   2023-09-18
41         1030      Laptop  60000.0      4.0      Delhi   2023-01-21
42         1018  Smartphone  15000.0      1.0  Bangalore   2021-04-16
43         1060      Laptop  45000.0      4.0       Pune   2022-05-11
44         1053      Tablet  45000.0      1.0    Chennai   2022-05-26
45         1038  Smartphone  45000.0      4.0       Pune   2022-04-11
46         1090      Laptop  30000.0      1.0     Mumbai   2022-11-07
47         1073      Tablet  30000.0      2.0     Mumbai   2021-08-14
48         1089  Smartphone  30000.0      NaN  Bangalore   2023-10-03
49         1018  Smartphone  30000.0      3.0      Delhi   2022-06-25
50         1038      Laptop  45000.0      4.0  Bangalore   2023-03-07
51         1066      Laptop  45000.0      NaN  Bangalore   2021-07-15
52         1044      Laptop  30000.0      3.0  Bangalore   2023-03-22
53         1012      Tablet  30000.0      3.0  Bangalore   2022-12-07
54         1091      Laptop  30000.0      1.0    Chennai   2021-04-01
55         1057  Smartphone  60000.0      2.0    Chennai   2021-04-01
56         1019  Smartphone  30000.0      2.0       Pune   2022-04-26
57         1091      Laptop  30000.0      NaN     Mumbai   2021-11-27
58         1071      Laptop  30000.0      2.0  Bangalore   2021-09-28
59         1060     Desktop  15000.0      4.0       Pune   2021-09-28
60         1038  Smartphone  30000.0      2.0     Mumbai   2022-06-10
61         1000      Tablet  15000.0      NaN      Delhi   2022-02-25
62         1002     Desktop  60000.0      2.0    Chennai   2023-06-05
63         1076      Laptop  30000.0      4.0     Mumbai   2021-01-16
64         1091      Laptop  30000.0      1.0      Delhi   2021-01-01
65         1061  Smartphone  15000.0      NaN     Mumbai   2022-11-22
66         1062      Laptop  30000.0      1.0    Chennai   2023-10-18
67         1024      Tablet  30000.0      1.0    Chennai   2021-10-13
68         1055  Smartphone  45000.0      1.0       Pune   2021-05-31
69         1032      Laptop  15000.0      3.0  Bangalore   2021-01-16
70         1037  Smartphone  30000.0      3.0     Mumbai   2023-09-18
71         1005      Laptop  15000.0      1.0     Mumbai   2021-06-15
72         1057      Laptop  15000.0      NaN      Delhi   2021-10-13
73         1043      Laptop  45000.0      4.0    Chennai   2021-03-02
74         1044      Tablet  30000.0      4.0     Mumbai   2022-06-25
75         1031      Tablet  15000.0      2.0    Chennai   2022-07-10
76         1044  Smartphone  30000.0      NaN     Mumbai   2021-05-01
77         1060      Laptop  60000.0      3.0       Pune   2023-02-20
78         1046      Laptop  15000.0      1.0  Bangalore   2022-10-08
79         1020      Tablet  15000.0      2.0     Mumbai   2021-12-12
80         1079      Laptop  45000.0      4.0    Chennai   2022-03-12
81         1084      Tablet  30000.0      3.0       Pune   2023-05-21
82         1074      Laptop  60000.0      3.0     Mumbai   2021-07-15
83         1035  Smartphone  30000.0      1.0      Delhi   2021-05-01
84         1098      Laptop  60000.0      4.0  Bangalore   2022-08-09
85         1018      Laptop  30000.0      NaN     Mumbai   2023-09-03
86         1019     Desktop  30000.0      3.0       Pune   2021-12-27
87         1056      Tablet  30000.0      1.0      Delhi   2023-12-17
88         1017      Laptop  45000.0      NaN       Pune   2021-11-12
89         1046      Laptop  45000.0      4.0       Pune   2021-02-15
90         1048     Desktop  45000.0      3.0      Delhi   2022-01-11
91         1013     Desktop  45000.0      NaN       Pune   2023-05-06
92         1014      Tablet  60000.0      NaN      Delhi   2022-02-25
93         1030     Desktop  30000.0      NaN     Mumbai   2022-06-25
94         1000  Smartphone  30000.0      3.0      Delhi   2023-11-02
95         1053     Desktop  30000.0      3.0      Delhi   2021-09-13
96         1002  Smartphone  45000.0      2.0  Bangalore   2022-09-08
97         1015      Tablet  45000.0      4.0      Delhi   2022-08-24
98         1086      Tablet  15000.0      1.0      Delhi   2022-07-10
99         1056      Tablet  30000.0      NaN     Mumbai   2022-05-11
100        1074      Tablet  60000.0      2.0  Bangalore   2021-08-29
101        1011      Tablet  30000.0      1.0    Chennai   2022-06-25
102        1073  Smartphone  15000.0      2.0     Mumbai   2021-12-27
103        1095  Smartphone  15000.0      3.0     Mumbai   2022-01-26
104        1015      Tablet  30000.0      NaN    Chennai   2023-04-21
105        1071     Desktop  60000.0      1.0      Delhi   2022-03-27
106        1075      Laptop  15000.0      1.0       Pune   2021-03-17
107        1023      Tablet  15000.0      1.0  Bangalore   2022-08-09
108        1027     Desktop  30000.0      1.0       Pune   2021-06-15
109        1007      Laptop  60000.0      1.0    Chennai   2023-02-20
110        1091      Tablet  15000.0      2.0     Mumbai   2023-11-17
111        1035      Tablet  60000.0      NaN     Mumbai   2021-05-16
112        1089  Smartphone  30000.0      3.0  Bangalore   2022-10-23
113        1007      Laptop  45000.0      3.0     Mumbai   2021-08-29
114        1057      Laptop  15000.0      3.0     Mumbai   2022-01-11
115        1059     Desktop  30000.0      3.0  Bangalore   2023-07-05
116        1049  Smartphone  30000.0      2.0  Bangalore   2022-11-07
117        1027  Smartphone  60000.0      4.0    Chennai   2023-08-04
118        1091  Smartphone  30000.0      NaN     Mumbai   2021-01-16
119        1040  Smartphone  15000.0      1.0     Mumbai   2023-03-07

In [5]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    125 non-null    int64
 1   Product       125 non-null    object
 2   Price         103 non-null    object
 3   Quantity      98 non-null     object
 4   City          125 non-null    object
 5   PurchaseDate  125 non-null    object
dtypes: int64(1), object(5)
memory usage: 6.0+ KB

In [6]:
ds.describe()#describe all info such as count,unique

        CustomerID
count   125.000000
mean   1045.936000
std      28.183942
min    1000.000000
25%    1019.000000
50%    1044.000000
75%    1071.000000
max    1098.000000

In [9]:
#Searching for duplicates
ds.duplicated().sum()#return count of duplicates

np.int64(0)

In [8]:
#Remove duplicates
ds.drop_duplicates(inplace = True)#return count of duplicate 0

In [10]:
#Name of columns(headers)
ds.columns

Index(['CustomerID', 'Product', 'Price', 'Quantity', 'City', 'PurchaseDate'], dtype='object')

In [12]:
#Handling Price
ds["Price"]=pd.to_numeric(ds["Price"],errors='coerce')#age convert into float
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 120 entries, 0 to 119
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    120 non-null    int64
 1   Product       120 non-null    object
 2   Price         97 non-null     float64
 3   Quantity      96 non-null     object
 4   City          120 non-null    object
 5   PurchaseDate  120 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 6.6+ KB

In [35]:
ds["Price"].unique()

array(['4.0', '3.0', '2.0', '5.0', nan], dtype=object)

In [51]:
#TO fill missing values
x=ds["Price"].median()
ds["Price"].fillna(x,inplace = True)#Fill the all missing values in column price
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 120 entries, 0 to 119
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    120 non-null    int64
 1   Product       120 non-null    object
 2   Price         120 non-null    float64
 3   Quantity      120 non-null    float64
 4   City          120 non-null    object
 5   PurchaseDate  120 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(2)
memory usage: 6.6+ KB

C:\Users\DELL\AppData\Local\Temp\ipykernel_2516\2752032551.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ds["Price"].fillna(x,inplace = True)#Fill the all missing values in column price

In [52]:
print(ds.to_string())

     CustomerID     Product    Price  Quantity       City PurchaseDate
0          1052     Desktop  30000.0       4.0  Bangalore   2021-06-30
1          1041     Desktop  30000.0       3.0      Delhi   2023-01-21
2          1057  Smartphone  30000.0       2.0  Bangalore   2023-04-06
3          1038      Tablet  45000.0       5.0    Chennai   2023-07-05
4          1013  Smartphone  45000.0       3.5     Mumbai   2022-04-11
5          1094      Laptop  60000.0       4.0     Mumbai   2022-03-12
6          1004      Laptop  30000.0       2.0    Chennai   2022-02-25
7          1034      Laptop  30000.0       2.0    Chennai   2022-12-22
8          1086      Laptop  30000.0       3.0      Delhi   2022-10-23
9          1092     Desktop  30000.0       3.0     Mumbai   2022-03-12
10         1074      Laptop  45000.0       3.5  Bangalore   2021-08-14
11         1017     Desktop  45000.0       3.5       Pune   2022-08-09
12         1075     Desktop  30000.0       5.0       Pune   2021-09-28
13         1008      Laptop  60000.0       5.0    Chennai   2021-09-13
14         1073      Laptop  15000.0       3.5      Delhi   2021-01-01
15         1057      Tablet  15000.0       3.5       Pune   2022-11-22
16         1016  Smartphone  60000.0       4.0     Mumbai   2023-09-03
17         1006      Laptop  30000.0       3.0    Chennai   2022-07-10
18         1045      Tablet  45000.0       5.0  Bangalore   2023-01-21
19         1012      Tablet  15000.0       3.0    Chennai   2023-07-20
20         1039  Smartphone  30000.0       3.0  Bangalore   2021-02-15
21         1041     Desktop  30000.0       3.5    Chennai   2021-01-01
22         1008      Laptop  60000.0       4.0    Chennai   2021-04-16
23         1049  Smartphone  30000.0       2.0    Chennai   2022-02-25
24         1026      Laptop  15000.0       4.0  Bangalore   2023-03-22
25         1065      Tablet  30000.0       4.0  Bangalore   2021-01-31
26         1004      Tablet  15000.0       3.0    Chennai   2022-04-11
27         1028     Desktop  60000.0       4.0       Pune   2021-05-16
28         1036      Tablet  60000.0       5.0      Delhi   2022-05-11
29         1037      Tablet  30000.0       3.0      Delhi   2023-03-22
30         1082  Smartphone  30000.0       5.0      Delhi   2022-04-11
31         1007      Laptop  30000.0       2.0  Bangalore   2023-01-06
32         1064      Laptop  30000.0       3.0  Bangalore   2021-04-01
33         1085  Smartphone  30000.0       2.0       Pune   2021-04-16
34         1016     Desktop  45000.0       3.0      Delhi   2023-08-19
35         1070      Laptop  45000.0       3.5      Delhi   2023-04-21
36         1088      Tablet  45000.0       4.0    Chennai   2023-09-18
37         1044      Laptop  45000.0       3.5  Bangalore   2023-05-21
38         1003      Tablet  15000.0       2.0      Delhi   2023-12-02
39         1035     Desktop  45000.0       4.0       Pune   2023-03-07
40         1069  Smartphone  60000.0       3.0       Pune   2023-09-18
41         1030      Laptop  60000.0       4.0      Delhi   2023-01-21
42         1018  Smartphone  15000.0       5.0  Bangalore   2021-04-16
43         1060      Laptop  45000.0       4.0       Pune   2022-05-11
44         1053      Tablet  45000.0       5.0    Chennai   2022-05-26
45         1038  Smartphone  45000.0       4.0       Pune   2022-04-11
46         1090      Laptop  30000.0       5.0     Mumbai   2022-11-07
47         1073      Tablet  30000.0       2.0     Mumbai   2021-08-14
48         1089  Smartphone  30000.0       3.5  Bangalore   2023-10-03
49         1018  Smartphone  30000.0       3.0      Delhi   2022-06-25
50         1038      Laptop  45000.0       4.0  Bangalore   2023-03-07
51         1066      Laptop  45000.0       3.5  Bangalore   2021-07-15
52         1044      Laptop  30000.0       3.0  Bangalore   2023-03-22
53         1012      Tablet  30000.0       3.0  Bangalore   2022-12-07
54         1091      Laptop  30000.0       5.0    Chennai   2021-04-01
55         1057  Smartphone  60000.0       2.0    Chennai   2021-04-01
56         1019  Smartphone  30000.0       2.0       Pune   2022-04-26
57         1091      Laptop  30000.0       3.5     Mumbai   2021-11-27
58         1071      Laptop  30000.0       2.0  Bangalore   2021-09-28
59         1060     Desktop  15000.0       4.0       Pune   2021-09-28
60         1038  Smartphone  30000.0       2.0     Mumbai   2022-06-10
61         1000      Tablet  15000.0       3.5      Delhi   2022-02-25
62         1002     Desktop  60000.0       2.0    Chennai   2023-06-05
63         1076      Laptop  30000.0       4.0     Mumbai   2021-01-16
64         1091      Laptop  30000.0       5.0      Delhi   2021-01-01
65         1061  Smartphone  15000.0       3.5     Mumbai   2022-11-22
66         1062      Laptop  30000.0       5.0    Chennai   2023-10-18
67         1024      Tablet  30000.0       5.0    Chennai   2021-10-13
68         1055  Smartphone  45000.0       5.0       Pune   2021-05-31
69         1032      Laptop  15000.0       3.0  Bangalore   2021-01-16
70         1037  Smartphone  30000.0       3.0     Mumbai   2023-09-18
71         1005      Laptop  15000.0       5.0     Mumbai   2021-06-15
72         1057      Laptop  15000.0       3.5      Delhi   2021-10-13
73         1043      Laptop  45000.0       4.0    Chennai   2021-03-02
74         1044      Tablet  30000.0       4.0     Mumbai   2022-06-25
75         1031      Tablet  15000.0       2.0    Chennai   2022-07-10
76         1044  Smartphone  30000.0       3.5     Mumbai   2021-05-01
77         1060      Laptop  60000.0       3.0       Pune   2023-02-20
78         1046      Laptop  15000.0       5.0  Bangalore   2022-10-08
79         1020      Tablet  15000.0       2.0     Mumbai   2021-12-12
80         1079      Laptop  45000.0       4.0    Chennai   2022-03-12
81         1084      Tablet  30000.0       3.0       Pune   2023-05-21
82         1074      Laptop  60000.0       3.0     Mumbai   2021-07-15
83         1035  Smartphone  30000.0       5.0      Delhi   2021-05-01
84         1098      Laptop  60000.0       4.0  Bangalore   2022-08-09
85         1018      Laptop  30000.0       3.5     Mumbai   2023-09-03
86         1019     Desktop  30000.0       3.0       Pune   2021-12-27
87         1056      Tablet  30000.0       5.0      Delhi   2023-12-17
88         1017      Laptop  45000.0       3.5       Pune   2021-11-12
89         1046      Laptop  45000.0       4.0       Pune   2021-02-15
90         1048     Desktop  45000.0       3.0      Delhi   2022-01-11
91         1013     Desktop  45000.0       3.5       Pune   2023-05-06
92         1014      Tablet  60000.0       3.5      Delhi   2022-02-25
93         1030     Desktop  30000.0       3.5     Mumbai   2022-06-25
94         1000  Smartphone  30000.0       3.0      Delhi   2023-11-02
95         1053     Desktop  30000.0       3.0      Delhi   2021-09-13
96         1002  Smartphone  45000.0       2.0  Bangalore   2022-09-08
97         1015      Tablet  45000.0       4.0      Delhi   2022-08-24
98         1086      Tablet  15000.0       5.0      Delhi   2022-07-10
99         1056      Tablet  30000.0       3.5     Mumbai   2022-05-11
100        1074      Tablet  60000.0       2.0  Bangalore   2021-08-29
101        1011      Tablet  30000.0       5.0    Chennai   2022-06-25
102        1073  Smartphone  15000.0       2.0     Mumbai   2021-12-27
103        1095  Smartphone  15000.0       3.0     Mumbai   2022-01-26
104        1015      Tablet  30000.0       3.5    Chennai   2023-04-21
105        1071     Desktop  60000.0       5.0      Delhi   2022-03-27
106        1075      Laptop  15000.0       5.0       Pune   2021-03-17
107        1023      Tablet  15000.0       5.0  Bangalore   2022-08-09
108        1027     Desktop  30000.0       5.0       Pune   2021-06-15
109        1007      Laptop  60000.0       5.0    Chennai   2023-02-20
110        1091      Tablet  15000.0       2.0     Mumbai   2023-11-17
111        1035      Tablet  60000.0       3.5     Mumbai   2021-05-16
112        1089  Smartphone  30000.0       3.0  Bangalore   2022-10-23
113        1007      Laptop  45000.0       3.0     Mumbai   2021-08-29
114        1057      Laptop  15000.0       3.0     Mumbai   2022-01-11
115        1059     Desktop  30000.0       3.0  Bangalore   2023-07-05
116        1049  Smartphone  30000.0       2.0  Bangalore   2022-11-07
117        1027  Smartphone  60000.0       4.0    Chennai   2023-08-04
118        1091  Smartphone  30000.0       3.5     Mumbai   2021-01-16
119        1040  Smartphone  15000.0       5.0     Mumbai   2023-03-07

In [24]:
ds["Quantity"].unique()

array(['4.0', '3.0', '2.0', '5.0', nan], dtype=object)

In [23]:
#Stanerdized City
ds["Quantity"] = ds["Quantity"].replace({
    "two":"4.0","1.0":"5.0","":"None"
})
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 120 entries, 0 to 119
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    120 non-null    int64
 1   Product       120 non-null    object
 2   Price         120 non-null    float64
 3   Quantity      96 non-null     object
 4   City          120 non-null    object
 5   PurchaseDate  120 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 6.6+ KB

In [25]:
print(ds.to_string())

     CustomerID     Product    Price Quantity       City PurchaseDate
0          1052     Desktop  30000.0      4.0  Bangalore   2021-06-30
1          1041     Desktop  30000.0      3.0      Delhi   2023-01-21
2          1057  Smartphone  30000.0      2.0  Bangalore   2023-04-06
3          1038      Tablet  45000.0      5.0    Chennai   2023-07-05
4          1013  Smartphone  45000.0      NaN     Mumbai   2022-04-11
5          1094      Laptop  60000.0      4.0     Mumbai   2022-03-12
6          1004      Laptop  30000.0      2.0    Chennai   2022-02-25
7          1034      Laptop  30000.0      2.0    Chennai   2022-12-22
8          1086      Laptop  30000.0      3.0      Delhi   2022-10-23
9          1092     Desktop  30000.0      3.0     Mumbai   2022-03-12
10         1074      Laptop  45000.0      NaN  Bangalore   2021-08-14
11         1017     Desktop  45000.0      NaN       Pune   2022-08-09
12         1075     Desktop  30000.0      5.0       Pune   2021-09-28
13         1008      Laptop  60000.0      5.0    Chennai   2021-09-13
14         1073      Laptop  15000.0      NaN      Delhi   2021-01-01
15         1057      Tablet  15000.0      NaN       Pune   2022-11-22
16         1016  Smartphone  60000.0      4.0     Mumbai   2023-09-03
17         1006      Laptop  30000.0      3.0    Chennai   2022-07-10
18         1045      Tablet  45000.0      5.0  Bangalore   2023-01-21
19         1012      Tablet  15000.0      3.0    Chennai   2023-07-20
20         1039  Smartphone  30000.0      3.0  Bangalore   2021-02-15
21         1041     Desktop  30000.0      NaN    Chennai   2021-01-01
22         1008      Laptop  60000.0      4.0    Chennai   2021-04-16
23         1049  Smartphone  30000.0      2.0    Chennai   2022-02-25
24         1026      Laptop  15000.0      4.0  Bangalore   2023-03-22
25         1065      Tablet  30000.0      4.0  Bangalore   2021-01-31
26         1004      Tablet  15000.0      3.0    Chennai   2022-04-11
27         1028     Desktop  60000.0      4.0       Pune   2021-05-16
28         1036      Tablet  60000.0      5.0      Delhi   2022-05-11
29         1037      Tablet  30000.0      3.0      Delhi   2023-03-22
30         1082  Smartphone  30000.0      5.0      Delhi   2022-04-11
31         1007      Laptop  30000.0      2.0  Bangalore   2023-01-06
32         1064      Laptop  30000.0      3.0  Bangalore   2021-04-01
33         1085  Smartphone  30000.0      2.0       Pune   2021-04-16
34         1016     Desktop  45000.0      3.0      Delhi   2023-08-19
35         1070      Laptop  45000.0      NaN      Delhi   2023-04-21
36         1088      Tablet  45000.0      4.0    Chennai   2023-09-18
37         1044      Laptop  45000.0      NaN  Bangalore   2023-05-21
38         1003      Tablet  15000.0      2.0      Delhi   2023-12-02
39         1035     Desktop  45000.0      4.0       Pune   2023-03-07
40         1069  Smartphone  60000.0      3.0       Pune   2023-09-18
41         1030      Laptop  60000.0      4.0      Delhi   2023-01-21
42         1018  Smartphone  15000.0      5.0  Bangalore   2021-04-16
43         1060      Laptop  45000.0      4.0       Pune   2022-05-11
44         1053      Tablet  45000.0      5.0    Chennai   2022-05-26
45         1038  Smartphone  45000.0      4.0       Pune   2022-04-11
46         1090      Laptop  30000.0      5.0     Mumbai   2022-11-07
47         1073      Tablet  30000.0      2.0     Mumbai   2021-08-14
48         1089  Smartphone  30000.0      NaN  Bangalore   2023-10-03
49         1018  Smartphone  30000.0      3.0      Delhi   2022-06-25
50         1038      Laptop  45000.0      4.0  Bangalore   2023-03-07
51         1066      Laptop  45000.0      NaN  Bangalore   2021-07-15
52         1044      Laptop  30000.0      3.0  Bangalore   2023-03-22
53         1012      Tablet  30000.0      3.0  Bangalore   2022-12-07
54         1091      Laptop  30000.0      5.0    Chennai   2021-04-01
55         1057  Smartphone  60000.0      2.0    Chennai   2021-04-01
56         1019  Smartphone  30000.0      2.0       Pune   2022-04-26
57         1091      Laptop  30000.0      NaN     Mumbai   2021-11-27
58         1071      Laptop  30000.0      2.0  Bangalore   2021-09-28
59         1060     Desktop  15000.0      4.0       Pune   2021-09-28
60         1038  Smartphone  30000.0      2.0     Mumbai   2022-06-10
61         1000      Tablet  15000.0      NaN      Delhi   2022-02-25
62         1002     Desktop  60000.0      2.0    Chennai   2023-06-05
63         1076      Laptop  30000.0      4.0     Mumbai   2021-01-16
64         1091      Laptop  30000.0      5.0      Delhi   2021-01-01
65         1061  Smartphone  15000.0      NaN     Mumbai   2022-11-22
66         1062      Laptop  30000.0      5.0    Chennai   2023-10-18
67         1024      Tablet  30000.0      5.0    Chennai   2021-10-13
68         1055  Smartphone  45000.0      5.0       Pune   2021-05-31
69         1032      Laptop  15000.0      3.0  Bangalore   2021-01-16
70         1037  Smartphone  30000.0      3.0     Mumbai   2023-09-18
71         1005      Laptop  15000.0      5.0     Mumbai   2021-06-15
72         1057      Laptop  15000.0      NaN      Delhi   2021-10-13
73         1043      Laptop  45000.0      4.0    Chennai   2021-03-02
74         1044      Tablet  30000.0      4.0     Mumbai   2022-06-25
75         1031      Tablet  15000.0      2.0    Chennai   2022-07-10
76         1044  Smartphone  30000.0      NaN     Mumbai   2021-05-01
77         1060      Laptop  60000.0      3.0       Pune   2023-02-20
78         1046      Laptop  15000.0      5.0  Bangalore   2022-10-08
79         1020      Tablet  15000.0      2.0     Mumbai   2021-12-12
80         1079      Laptop  45000.0      4.0    Chennai   2022-03-12
81         1084      Tablet  30000.0      3.0       Pune   2023-05-21
82         1074      Laptop  60000.0      3.0     Mumbai   2021-07-15
83         1035  Smartphone  30000.0      5.0      Delhi   2021-05-01
84         1098      Laptop  60000.0      4.0  Bangalore   2022-08-09
85         1018      Laptop  30000.0      NaN     Mumbai   2023-09-03
86         1019     Desktop  30000.0      3.0       Pune   2021-12-27
87         1056      Tablet  30000.0      5.0      Delhi   2023-12-17
88         1017      Laptop  45000.0      NaN       Pune   2021-11-12
89         1046      Laptop  45000.0      4.0       Pune   2021-02-15
90         1048     Desktop  45000.0      3.0      Delhi   2022-01-11
91         1013     Desktop  45000.0      NaN       Pune   2023-05-06
92         1014      Tablet  60000.0      NaN      Delhi   2022-02-25
93         1030     Desktop  30000.0      NaN     Mumbai   2022-06-25
94         1000  Smartphone  30000.0      3.0      Delhi   2023-11-02
95         1053     Desktop  30000.0      3.0      Delhi   2021-09-13
96         1002  Smartphone  45000.0      2.0  Bangalore   2022-09-08
97         1015      Tablet  45000.0      4.0      Delhi   2022-08-24
98         1086      Tablet  15000.0      5.0      Delhi   2022-07-10
99         1056      Tablet  30000.0      NaN     Mumbai   2022-05-11
100        1074      Tablet  60000.0      2.0  Bangalore   2021-08-29
101        1011      Tablet  30000.0      5.0    Chennai   2022-06-25
102        1073  Smartphone  15000.0      2.0     Mumbai   2021-12-27
103        1095  Smartphone  15000.0      3.0     Mumbai   2022-01-26
104        1015      Tablet  30000.0      NaN    Chennai   2023-04-21
105        1071     Desktop  60000.0      5.0      Delhi   2022-03-27
106        1075      Laptop  15000.0      5.0       Pune   2021-03-17
107        1023      Tablet  15000.0      5.0  Bangalore   2022-08-09
108        1027     Desktop  30000.0      5.0       Pune   2021-06-15
109        1007      Laptop  60000.0      5.0    Chennai   2023-02-20
110        1091      Tablet  15000.0      2.0     Mumbai   2023-11-17
111        1035      Tablet  60000.0      NaN     Mumbai   2021-05-16
112        1089  Smartphone  30000.0      3.0  Bangalore   2022-10-23
113        1007      Laptop  45000.0      3.0     Mumbai   2021-08-29
114        1057      Laptop  15000.0      3.0     Mumbai   2022-01-11
115        1059     Desktop  30000.0      3.0  Bangalore   2023-07-05
116        1049  Smartphone  30000.0      2.0  Bangalore   2022-11-07
117        1027  Smartphone  60000.0      4.0    Chennai   2023-08-04
118        1091  Smartphone  30000.0      NaN     Mumbai   2021-01-16
119        1040  Smartphone  15000.0      5.0     Mumbai   2023-03-07

In [33]:
ds.columns

Index(['CustomerID', 'Product', 'Price', 'Quantity', 'City', 'PurchaseDate'], dtype='object')

In [39]:
#Handling Quantity Column
ds["Quantity"].fillna("-",inplace = True)
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 120 entries, 0 to 119
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    120 non-null    int64
 1   Product       120 non-null    object
 2   Price         120 non-null    float64
 3   Quantity      120 non-null    object
 4   City          120 non-null    object
 5   PurchaseDate  120 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 6.6+ KB

In [38]:
print(ds.to_string())

     CustomerID     Product    Price Quantity       City PurchaseDate
0          1052     Desktop  30000.0      4.0  Bangalore   2021-06-30
1          1041     Desktop  30000.0      3.0      Delhi   2023-01-21
2          1057  Smartphone  30000.0      2.0  Bangalore   2023-04-06
3          1038      Tablet  45000.0      5.0    Chennai   2023-07-05
4          1013  Smartphone  45000.0        -     Mumbai   2022-04-11
5          1094      Laptop  60000.0      4.0     Mumbai   2022-03-12
6          1004      Laptop  30000.0      2.0    Chennai   2022-02-25
7          1034      Laptop  30000.0      2.0    Chennai   2022-12-22
8          1086      Laptop  30000.0      3.0      Delhi   2022-10-23
9          1092     Desktop  30000.0      3.0     Mumbai   2022-03-12
10         1074      Laptop  45000.0        -  Bangalore   2021-08-14
11         1017     Desktop  45000.0        -       Pune   2022-08-09
12         1075     Desktop  30000.0      5.0       Pune   2021-09-28
13         1008      Laptop  60000.0      5.0    Chennai   2021-09-13
14         1073      Laptop  15000.0        -      Delhi   2021-01-01
15         1057      Tablet  15000.0        -       Pune   2022-11-22
16         1016  Smartphone  60000.0      4.0     Mumbai   2023-09-03
17         1006      Laptop  30000.0      3.0    Chennai   2022-07-10
18         1045      Tablet  45000.0      5.0  Bangalore   2023-01-21
19         1012      Tablet  15000.0      3.0    Chennai   2023-07-20
20         1039  Smartphone  30000.0      3.0  Bangalore   2021-02-15
21         1041     Desktop  30000.0        -    Chennai   2021-01-01
22         1008      Laptop  60000.0      4.0    Chennai   2021-04-16
23         1049  Smartphone  30000.0      2.0    Chennai   2022-02-25
24         1026      Laptop  15000.0      4.0  Bangalore   2023-03-22
25         1065      Tablet  30000.0      4.0  Bangalore   2021-01-31
26         1004      Tablet  15000.0      3.0    Chennai   2022-04-11
27         1028     Desktop  60000.0      4.0       Pune   2021-05-16
28         1036      Tablet  60000.0      5.0      Delhi   2022-05-11
29         1037      Tablet  30000.0      3.0      Delhi   2023-03-22
30         1082  Smartphone  30000.0      5.0      Delhi   2022-04-11
31         1007      Laptop  30000.0      2.0  Bangalore   2023-01-06
32         1064      Laptop  30000.0      3.0  Bangalore   2021-04-01
33         1085  Smartphone  30000.0      2.0       Pune   2021-04-16
34         1016     Desktop  45000.0      3.0      Delhi   2023-08-19
35         1070      Laptop  45000.0        -      Delhi   2023-04-21
36         1088      Tablet  45000.0      4.0    Chennai   2023-09-18
37         1044      Laptop  45000.0        -  Bangalore   2023-05-21
38         1003      Tablet  15000.0      2.0      Delhi   2023-12-02
39         1035     Desktop  45000.0      4.0       Pune   2023-03-07
40         1069  Smartphone  60000.0      3.0       Pune   2023-09-18
41         1030      Laptop  60000.0      4.0      Delhi   2023-01-21
42         1018  Smartphone  15000.0      5.0  Bangalore   2021-04-16
43         1060      Laptop  45000.0      4.0       Pune   2022-05-11
44         1053      Tablet  45000.0      5.0    Chennai   2022-05-26
45         1038  Smartphone  45000.0      4.0       Pune   2022-04-11
46         1090      Laptop  30000.0      5.0     Mumbai   2022-11-07
47         1073      Tablet  30000.0      2.0     Mumbai   2021-08-14
48         1089  Smartphone  30000.0        -  Bangalore   2023-10-03
49         1018  Smartphone  30000.0      3.0      Delhi   2022-06-25
50         1038      Laptop  45000.0      4.0  Bangalore   2023-03-07
51         1066      Laptop  45000.0        -  Bangalore   2021-07-15
52         1044      Laptop  30000.0      3.0  Bangalore   2023-03-22
53         1012      Tablet  30000.0      3.0  Bangalore   2022-12-07
54         1091      Laptop  30000.0      5.0    Chennai   2021-04-01
55         1057  Smartphone  60000.0      2.0    Chennai   2021-04-01
56         1019  Smartphone  30000.0      2.0       Pune   2022-04-26
57         1091      Laptop  30000.0        -     Mumbai   2021-11-27
58         1071      Laptop  30000.0      2.0  Bangalore   2021-09-28
59         1060     Desktop  15000.0      4.0       Pune   2021-09-28
60         1038  Smartphone  30000.0      2.0     Mumbai   2022-06-10
61         1000      Tablet  15000.0        -      Delhi   2022-02-25
62         1002     Desktop  60000.0      2.0    Chennai   2023-06-05
63         1076      Laptop  30000.0      4.0     Mumbai   2021-01-16
64         1091      Laptop  30000.0      5.0      Delhi   2021-01-01
65         1061  Smartphone  15000.0        -     Mumbai   2022-11-22
66         1062      Laptop  30000.0      5.0    Chennai   2023-10-18
67         1024      Tablet  30000.0      5.0    Chennai   2021-10-13
68         1055  Smartphone  45000.0      5.0       Pune   2021-05-31
69         1032      Laptop  15000.0      3.0  Bangalore   2021-01-16
70         1037  Smartphone  30000.0      3.0     Mumbai   2023-09-18
71         1005      Laptop  15000.0      5.0     Mumbai   2021-06-15
72         1057      Laptop  15000.0        -      Delhi   2021-10-13
73         1043      Laptop  45000.0      4.0    Chennai   2021-03-02
74         1044      Tablet  30000.0      4.0     Mumbai   2022-06-25
75         1031      Tablet  15000.0      2.0    Chennai   2022-07-10
76         1044  Smartphone  30000.0        -     Mumbai   2021-05-01
77         1060      Laptop  60000.0      3.0       Pune   2023-02-20
78         1046      Laptop  15000.0      5.0  Bangalore   2022-10-08
79         1020      Tablet  15000.0      2.0     Mumbai   2021-12-12
80         1079      Laptop  45000.0      4.0    Chennai   2022-03-12
81         1084      Tablet  30000.0      3.0       Pune   2023-05-21
82         1074      Laptop  60000.0      3.0     Mumbai   2021-07-15
83         1035  Smartphone  30000.0      5.0      Delhi   2021-05-01
84         1098      Laptop  60000.0      4.0  Bangalore   2022-08-09
85         1018      Laptop  30000.0        -     Mumbai   2023-09-03
86         1019     Desktop  30000.0      3.0       Pune   2021-12-27
87         1056      Tablet  30000.0      5.0      Delhi   2023-12-17
88         1017      Laptop  45000.0        -       Pune   2021-11-12
89         1046      Laptop  45000.0      4.0       Pune   2021-02-15
90         1048     Desktop  45000.0      3.0      Delhi   2022-01-11
91         1013     Desktop  45000.0        -       Pune   2023-05-06
92         1014      Tablet  60000.0        -      Delhi   2022-02-25
93         1030     Desktop  30000.0        -     Mumbai   2022-06-25
94         1000  Smartphone  30000.0      3.0      Delhi   2023-11-02
95         1053     Desktop  30000.0      3.0      Delhi   2021-09-13
96         1002  Smartphone  45000.0      2.0  Bangalore   2022-09-08
97         1015      Tablet  45000.0      4.0      Delhi   2022-08-24
98         1086      Tablet  15000.0      5.0      Delhi   2022-07-10
99         1056      Tablet  30000.0        -     Mumbai   2022-05-11
100        1074      Tablet  60000.0      2.0  Bangalore   2021-08-29
101        1011      Tablet  30000.0      5.0    Chennai   2022-06-25
102        1073  Smartphone  15000.0      2.0     Mumbai   2021-12-27
103        1095  Smartphone  15000.0      3.0     Mumbai   2022-01-26
104        1015      Tablet  30000.0        -    Chennai   2023-04-21
105        1071     Desktop  60000.0      5.0      Delhi   2022-03-27
106        1075      Laptop  15000.0      5.0       Pune   2021-03-17
107        1023      Tablet  15000.0      5.0  Bangalore   2022-08-09
108        1027     Desktop  30000.0      5.0       Pune   2021-06-15
109        1007      Laptop  60000.0      5.0    Chennai   2023-02-20
110        1091      Tablet  15000.0      2.0     Mumbai   2023-11-17
111        1035      Tablet  60000.0        -     Mumbai   2021-05-16
112        1089  Smartphone  30000.0      3.0  Bangalore   2022-10-23
113        1007      Laptop  45000.0      3.0     Mumbai   2021-08-29
114        1057      Laptop  15000.0      3.0     Mumbai   2022-01-11
115        1059     Desktop  30000.0      3.0  Bangalore   2023-07-05
116        1049  Smartphone  30000.0      2.0  Bangalore   2022-11-07
117        1027  Smartphone  60000.0      4.0    Chennai   2023-08-04
118        1091  Smartphone  30000.0        -     Mumbai   2021-01-16
119        1040  Smartphone  15000.0      5.0     Mumbai   2023-03-07

In [41]:
#Handling Purchasedate column
ds["PurchaseDate"]=pd.to_datetime(ds["PurchaseDate"],errors='coerce')#Dtype of Join_date convert into datetime
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 120 entries, 0 to 119
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    120 non-null    int64
 1   Product       120 non-null    object
 2   Price         120 non-null    float64
 3   Quantity      120 non-null    object
 4   City          120 non-null    object
 5   PurchaseDate  120 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(1), object(3)
memory usage: 6.6+ KB

In [42]:
#Handling Quantity column
ds["Quantity"]=pd.to_numeric(ds["Quantity"],errors='coerce')#Dtype of Quantity convert object into float
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 120 entries, 0 to 119
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    120 non-null    int64
 1   Product       120 non-null    object
 2   Price         120 non-null    float64
 3   Quantity      96 non-null     float64
 4   City          120 non-null    object
 5   PurchaseDate  120 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(2)
memory usage: 6.6+ KB

In [45]:
#unique values in Department
ds["CustomerID"].unique()

array([1052, 1041, 1057, 1038, 1013, 1094, 1004, 1034, 1086, 1092, 1074,
       1017, 1075, 1008, 1073, 1016, 1006, 1045, 1012, 1039, 1049, 1026,
       1065, 1028, 1036, 1037, 1082, 1007, 1064, 1085, 1070, 1088, 1044,
       1003, 1035, 1069, 1030, 1018, 1060, 1053, 1090, 1089, 1066, 1091,
       1019, 1071, 1000, 1002, 1076, 1061, 1062, 1024, 1055, 1032, 1005,
       1043, 1031, 1046, 1020, 1079, 1084, 1098, 1056, 1048, 1014, 1015,
       1011, 1095, 1023, 1027, 1059, 1040])

In [46]:
#Mode of col CustomerID
y=ds["CustomerID"].mode()[0]
y

np.int64(1057)

In [49]:
#Handling misssing values of CustomerID column
ds["CustomerID"].fillna(y,inplace=True)
print(ds.to_string())

     CustomerID     Product    Price  Quantity       City PurchaseDate
0          1052     Desktop  30000.0       4.0  Bangalore   2021-06-30
1          1041     Desktop  30000.0       3.0      Delhi   2023-01-21
2          1057  Smartphone  30000.0       2.0  Bangalore   2023-04-06
3          1038      Tablet  45000.0       5.0    Chennai   2023-07-05
4          1013  Smartphone  45000.0       NaN     Mumbai   2022-04-11
5          1094      Laptop  60000.0       4.0     Mumbai   2022-03-12
6          1004      Laptop  30000.0       2.0    Chennai   2022-02-25
7          1034      Laptop  30000.0       2.0    Chennai   2022-12-22
8          1086      Laptop  30000.0       3.0      Delhi   2022-10-23
9          1092     Desktop  30000.0       3.0     Mumbai   2022-03-12
10         1074      Laptop  45000.0       NaN  Bangalore   2021-08-14
11         1017     Desktop  45000.0       NaN       Pune   2022-08-09
12         1075     Desktop  30000.0       5.0       Pune   2021-09-28
13         1008      Laptop  60000.0       5.0    Chennai   2021-09-13
14         1073      Laptop  15000.0       NaN      Delhi   2021-01-01
15         1057      Tablet  15000.0       NaN       Pune   2022-11-22
16         1016  Smartphone  60000.0       4.0     Mumbai   2023-09-03
17         1006      Laptop  30000.0       3.0    Chennai   2022-07-10
18         1045      Tablet  45000.0       5.0  Bangalore   2023-01-21
19         1012      Tablet  15000.0       3.0    Chennai   2023-07-20
20         1039  Smartphone  30000.0       3.0  Bangalore   2021-02-15
21         1041     Desktop  30000.0       NaN    Chennai   2021-01-01
22         1008      Laptop  60000.0       4.0    Chennai   2021-04-16
23         1049  Smartphone  30000.0       2.0    Chennai   2022-02-25
24         1026      Laptop  15000.0       4.0  Bangalore   2023-03-22
25         1065      Tablet  30000.0       4.0  Bangalore   2021-01-31
26         1004      Tablet  15000.0       3.0    Chennai   2022-04-11
27         1028     Desktop  60000.0       4.0       Pune   2021-05-16
28         1036      Tablet  60000.0       5.0      Delhi   2022-05-11
29         1037      Tablet  30000.0       3.0      Delhi   2023-03-22
30         1082  Smartphone  30000.0       5.0      Delhi   2022-04-11
31         1007      Laptop  30000.0       2.0  Bangalore   2023-01-06
32         1064      Laptop  30000.0       3.0  Bangalore   2021-04-01
33         1085  Smartphone  30000.0       2.0       Pune   2021-04-16
34         1016     Desktop  45000.0       3.0      Delhi   2023-08-19
35         1070      Laptop  45000.0       NaN      Delhi   2023-04-21
36         1088      Tablet  45000.0       4.0    Chennai   2023-09-18
37         1044      Laptop  45000.0       NaN  Bangalore   2023-05-21
38         1003      Tablet  15000.0       2.0      Delhi   2023-12-02
39         1035     Desktop  45000.0       4.0       Pune   2023-03-07
40         1069  Smartphone  60000.0       3.0       Pune   2023-09-18
41         1030      Laptop  60000.0       4.0      Delhi   2023-01-21
42         1018  Smartphone  15000.0       5.0  Bangalore   2021-04-16
43         1060      Laptop  45000.0       4.0       Pune   2022-05-11
44         1053      Tablet  45000.0       5.0    Chennai   2022-05-26
45         1038  Smartphone  45000.0       4.0       Pune   2022-04-11
46         1090      Laptop  30000.0       5.0     Mumbai   2022-11-07
47         1073      Tablet  30000.0       2.0     Mumbai   2021-08-14
48         1089  Smartphone  30000.0       NaN  Bangalore   2023-10-03
49         1018  Smartphone  30000.0       3.0      Delhi   2022-06-25
50         1038      Laptop  45000.0       4.0  Bangalore   2023-03-07
51         1066      Laptop  45000.0       NaN  Bangalore   2021-07-15
52         1044      Laptop  30000.0       3.0  Bangalore   2023-03-22
53         1012      Tablet  30000.0       3.0  Bangalore   2022-12-07
54         1091      Laptop  30000.0       5.0    Chennai   2021-04-01
55         1057  Smartphone  60000.0       2.0    Chennai   2021-04-01
56         1019  Smartphone  30000.0       2.0       Pune   2022-04-26
57         1091      Laptop  30000.0       NaN     Mumbai   2021-11-27
58         1071      Laptop  30000.0       2.0  Bangalore   2021-09-28
59         1060     Desktop  15000.0       4.0       Pune   2021-09-28
60         1038  Smartphone  30000.0       2.0     Mumbai   2022-06-10
61         1000      Tablet  15000.0       NaN      Delhi   2022-02-25
62         1002     Desktop  60000.0       2.0    Chennai   2023-06-05
63         1076      Laptop  30000.0       4.0     Mumbai   2021-01-16
64         1091      Laptop  30000.0       5.0      Delhi   2021-01-01
65         1061  Smartphone  15000.0       NaN     Mumbai   2022-11-22
66         1062      Laptop  30000.0       5.0    Chennai   2023-10-18
67         1024      Tablet  30000.0       5.0    Chennai   2021-10-13
68         1055  Smartphone  45000.0       5.0       Pune   2021-05-31
69         1032      Laptop  15000.0       3.0  Bangalore   2021-01-16
70         1037  Smartphone  30000.0       3.0     Mumbai   2023-09-18
71         1005      Laptop  15000.0       5.0     Mumbai   2021-06-15
72         1057      Laptop  15000.0       NaN      Delhi   2021-10-13
73         1043      Laptop  45000.0       4.0    Chennai   2021-03-02
74         1044      Tablet  30000.0       4.0     Mumbai   2022-06-25
75         1031      Tablet  15000.0       2.0    Chennai   2022-07-10
76         1044  Smartphone  30000.0       NaN     Mumbai   2021-05-01
77         1060      Laptop  60000.0       3.0       Pune   2023-02-20
78         1046      Laptop  15000.0       5.0  Bangalore   2022-10-08
79         1020      Tablet  15000.0       2.0     Mumbai   2021-12-12
80         1079      Laptop  45000.0       4.0    Chennai   2022-03-12
81         1084      Tablet  30000.0       3.0       Pune   2023-05-21
82         1074      Laptop  60000.0       3.0     Mumbai   2021-07-15
83         1035  Smartphone  30000.0       5.0      Delhi   2021-05-01
84         1098      Laptop  60000.0       4.0  Bangalore   2022-08-09
85         1018      Laptop  30000.0       NaN     Mumbai   2023-09-03
86         1019     Desktop  30000.0       3.0       Pune   2021-12-27
87         1056      Tablet  30000.0       5.0      Delhi   2023-12-17
88         1017      Laptop  45000.0       NaN       Pune   2021-11-12
89         1046      Laptop  45000.0       4.0       Pune   2021-02-15
90         1048     Desktop  45000.0       3.0      Delhi   2022-01-11
91         1013     Desktop  45000.0       NaN       Pune   2023-05-06
92         1014      Tablet  60000.0       NaN      Delhi   2022-02-25
93         1030     Desktop  30000.0       NaN     Mumbai   2022-06-25
94         1000  Smartphone  30000.0       3.0      Delhi   2023-11-02
95         1053     Desktop  30000.0       3.0      Delhi   2021-09-13
96         1002  Smartphone  45000.0       2.0  Bangalore   2022-09-08
97         1015      Tablet  45000.0       4.0      Delhi   2022-08-24
98         1086      Tablet  15000.0       5.0      Delhi   2022-07-10
99         1056      Tablet  30000.0       NaN     Mumbai   2022-05-11
100        1074      Tablet  60000.0       2.0  Bangalore   2021-08-29
101        1011      Tablet  30000.0       5.0    Chennai   2022-06-25
102        1073  Smartphone  15000.0       2.0     Mumbai   2021-12-27
103        1095  Smartphone  15000.0       3.0     Mumbai   2022-01-26
104        1015      Tablet  30000.0       NaN    Chennai   2023-04-21
105        1071     Desktop  60000.0       5.0      Delhi   2022-03-27
106        1075      Laptop  15000.0       5.0       Pune   2021-03-17
107        1023      Tablet  15000.0       5.0  Bangalore   2022-08-09
108        1027     Desktop  30000.0       5.0       Pune   2021-06-15
109        1007      Laptop  60000.0       5.0    Chennai   2023-02-20
110        1091      Tablet  15000.0       2.0     Mumbai   2023-11-17
111        1035      Tablet  60000.0       NaN     Mumbai   2021-05-16
112        1089  Smartphone  30000.0       3.0  Bangalore   2022-10-23
113        1007      Laptop  45000.0       3.0     Mumbai   2021-08-29
114        1057      Laptop  15000.0       3.0     Mumbai   2022-01-11
115        1059     Desktop  30000.0       3.0  Bangalore   2023-07-05
116        1049  Smartphone  30000.0       2.0  Bangalore   2022-11-07
117        1027  Smartphone  60000.0       4.0    Chennai   2023-08-04
118        1091  Smartphone  30000.0       NaN     Mumbai   2021-01-16
119        1040  Smartphone  15000.0       5.0     Mumbai   2023-03-07

C:\Users\DELL\AppData\Local\Temp\ipykernel_2516\474290489.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ds["CustomerID"].fillna(y,inplace=True)

In [53]:
#Save data into new file
ds.to_csv("product_dataset_Task2.csv")